---
# enable recommended policies and set them as monitor
# recommendedPolicies:
#   enabled: True
#   skipAdditionalNamespaces: []
#   defaultPolicyMode: "monitor"
common:
  cattle:
    systemDefaultRegistry: mtr.devops.telekom.de
policyServer:
  replicaCount: 1
  image:
    repository: "kubewarden/kubewarden-policy-server"
    tag: "v1.4.0"
  serviceAccountName: policy-server
  permissions:
    - apiGroup: ""
      resources:
        - namespaces
        - pods
        - secrets
        - services
    - apiGroup: "networking.k8s.io"
      resources:
        - ingresses
    - apiGroup: "policies.kubewarden.io"
      resources:
        - clusteradmissionpolicies
        - admissionpolicies
        - policyservers
      verbs:
        - get
        - list
        - watch
    - apiGroup: "policies.kubewarden.io"
      resources:
        - policyservers/status
      verbs:
        - update
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
crdVersion: "policies.kubewarden.io/v1"
recommendedPolicies:
  enabled: False
